import Link from "next/link";

export const metadata = {
  title: "Auth",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
  return (
    <section className="bg-gray-200 h-screen">
        <div className="flex flex-col items-center justify-center h-screen gap-5">
            <Link href={`/`}>Logo Store</Link>
            {children}
        </div>
    </section>
  );
}
